project_id = "besoyrwozpzzhtxliyqz"

[functions.seed-users]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.gmail-oauth-init]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.gmail-refresh-token]
verify_jwt = false

[functions.get-google-client-id]
verify_jwt = false