// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://besoyrwozpzzhtxliyqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlc295cndvenB6emh0eGxpeXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODUzMTEsImV4cCI6MjA3MzM2MTMxMX0.t8uWs8GmM2Ih9sN5IPBOnE9MWatKL__zDvswgtlSJ7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});