name: Keep App Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes (fréquence minimale fiable)
  workflow_dispatch:       # permet de lancer manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: keepalive
      cancel-in-progress: true
    steps:
      - name: Ping health endpoint
        run: |
          curl -fsS https://ton-domaine/health >/dev/null
